### ISSUE TITLE
请问methodCount 这个是什么意思？

### ISSUE THREAD

**Issue by 1034205079** [IIIImmmyyy/HybirdCLR-Hook#1]
请问，methodCount 是cs文件中某个方法的数量吗？还是别的什么意思呢？谢谢

**Comment by IIIImmmyyy** [comment]
cs 文件的函数数量 无论静态还是非静态 按数量即可， 如果是非静态情况下 第一个为klass的实例 这个与il2cpp 本身的hook一致

**Comment by RockLee0719** [comment]
参数的数量
